services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mongodb_dev_Forensics
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=Forensics_db

volumes:
  mongodb_data:
